import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";
import ChartComponent from "../components/ChartComponent";
import FormInputSalary from "../components/FormInputSalary";
import useAuthContext from "../hooks/useAuthContext";
import styles from "../styles/Home.module.css";
import "react-responsive-modal/styles.css";
import { Modal } from "react-responsive-modal";
import Sliders from "../components/Sliders";
import Image from "next/image";

const Container = styled.main`
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr;
  height: calc(100vh - 48px);

  @media screen and (max-width: 600px) {
    grid-template-columns: 1fr;
    grid-template-rows: 1fr 1fr;
  }
`;

const ContainerForm = styled.div`
  display: flex;
  align-items: center;
  border-right: 2px solid gray;
  flex-direction: column;
`;

const Header = styled.header`
  height: 48px;
  display: flex;
  align-items: center;
  background-color: #354259;
  margin: 0;
`;

const ContainerChart = styled.div`
  display: flex;
  align-items: center;
`;

const Home = () => {
  const { user } = useAuthContext();

  const [calculatedResult, setCalculatedResult] = useState({ fifty: 0, thirty: 0, twenty: 0 });
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title className="">Budgeting Rule App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="mt-10">
        <p className="ml-10 text-2xl text-white flex-1">Budgeting Rule App</p>
        <Image src="/login.svg" width={32} height={32} />
      </Header>

      <Container>
        <ContainerForm>
          <h1 className=" text-4xl text-center mt-10">
            What the heck is <span className=" text-note-300 text-5xl">Budgeting Rule ?</span>
          </h1>
          <div onClick={() => setIsModalOpen(true)} className="cursor-pointer w-8 h-8">
            <Image src="/info_icon.svg" width={30} height={30} />
          </div>
          <FormInputSalary onChange={(data) => setCalculatedResult(data)} />
        </ContainerForm>
        <ContainerChart>
          <ChartComponent data={calculatedResult} />
        </ContainerChart>
      </Container>

      <Modal open={isModalOpen} onClose={() => setIsModalOpen(false)}>
        <div className="">
          <Sliders />
        </div>
      </Modal>
    </div>
  );
};

export default Home;
